modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/LatvianModder/Sluice/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "ftbsluice"
version = "${version}"
displayName = "FTB Sluice"
authors = "FTB Team, LatvianModder, ErrorMikey"
description = '''
A simple mod that adds Sluice block which lets you wash different blocks to get items out of them
'''
license = "GNU LGPLv3"

[[dependencies.ftbsluice]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbsluice]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"
